DIR_PATH = "input/"
DATASET_PATH = "cezanne2photo"
BASE_DATASET_PATH = DIR_PATH + DATASET_PATH
X_DATASET = "trainA"
Y_DATASET = "trainB"

BATCH_SIZE = 18
N_WORKERS = 0

IMG_SIZE = 128
LR = 0.0002
BETA1 = 0.5
BETA2 = 0.999

EPOCHS = 100